from typing import List, Dict
import os
import hashlib
from agent.models.embedding_model import EmbeddingModel
from agent.rag.text_splitter import ThreeLayerSplitter
from agent.rag.milvus_manage import MilvusManage
from agent.utils.logger_handler import get_logger
from agent.utils.path_handler import get_absolute_path

logger = get_logger()

class DataEmbedding:
    def __init__(self, model_name: str = "zhipuai", dimensions: int = 1024):
        self.embedding_model = EmbeddingModel(model_name=model_name, dimensions=dimensions)
        self.milvus_manager = MilvusManage()
        self.splitter = ThreeLayerSplitter()
        self.md5_file = get_absolute_path("src/agent/data/processed_md5.txt")
        
        # Ensure data directory exists
        os.makedirs(os.path.dirname(self.md5_file), exist_ok=True)

    def _get_text_md5(self, text: str) -> str:
        """计算文本的 MD5 值"""
        return hashlib.md5(text.encode("utf-8")).hexdigest()

    def _is_processed(self, md5_val: str) -> bool:
        """检查 MD5 是否已存在于持久化文件中"""
        if not os.path.exists(self.md5_file):
            return False
        with open(self.md5_file, "r", encoding="utf-8") as f:
            processed_md5s = f.read().splitlines()
        return md5_val in processed_md5s

    def _mark_as_processed(self, md5_val: str):
        """将 MD5 值存入持久化文件"""
        with open(self.md5_file, "a", encoding="utf-8") as f:
            f.write(md5_val + "\n")

    def process_document(self, doc_input: str | List[Dict], metadata: Dict = None):
        """
        Process document: split into 3 layers, generate embeddings, and store in Milvus.
        Includes MD5 check to skip processed content.
        
        doc_input: Can be raw text string or a list of dictionaries from DocumentLoader.
        """
        metadata = metadata or {}
        # 1. Extract text if input is a list (from DocumentLoader)
        if isinstance(doc_input, list):
            doc_text = "\n".join([d.get("text", "") for d in doc_input])
            # Merge metadata if not provided
            if not metadata and doc_input:
                metadata = {
                    "filename": doc_input[0].get("filename"),
                    "file_type": doc_input[0].get("file_type"),
                    "file_path": doc_input[0].get("file_path"),
                }
        else:
            doc_text = doc_input

        # 2. MD5 Check
        doc_md5 = self._get_text_md5(doc_text)
        if self._is_processed(doc_md5):
            logger.info(f"Document '{metadata.get('filename', 'unknown')}' with MD5 {doc_md5} already processed. Skipping.")
            return

        # 3. Split text into 3 layers
        all_chunks = self.splitter.split(doc_text, metadata)
        
        # 2. Filter layer 2 chunks (deduplication)
        l2_chunks = [c for c in all_chunks if c["chunk_level"] == 2]
        l2_chunks = self.splitter.deduplicate_layer2(l2_chunks)
        
        # Combine all chunks back (if deduplication removed any)
        other_chunks = [c for c in all_chunks if c["chunk_level"] != 2]
        processed_chunks = l2_chunks + other_chunks

        # 3. Generate dense embeddings (BM25 is handled by Milvus automatically via Function)
        logger.info(f"Generating dense embeddings for {len(processed_chunks)} chunks...")
        
        texts = [c["text"] for c in processed_chunks]
        dense_embeddings = self.embedding_model.embed_documents(texts)

        # 4. Prepare data for Milvus
        milvus_data = []
        for i, chunk in enumerate(processed_chunks):
            chunk_data = {
                "text": chunk["text"],
                "text_dense": dense_embeddings[i],
                # text_sparse is generated by Milvus function
                "filename": chunk.get("filename") or "",
                "file_type": chunk.get("file_type") or "",
                "file_path": chunk.get("file_path") or "",
                "page_number": int(chunk.get("page_number") or 0),
                "chunk_idx": i,
                "chunk_id": chunk["chunk_id"],
                "parent_chunk_id": chunk.get("parent_chunk_id") or "",
                "root_chunk_id": chunk.get("root_chunk_id") or "",
                "chunk_level": int(chunk["chunk_level"]),
            }
            milvus_data.append(chunk_data)

        # 5. Insert into Milvus
        if not self.milvus_manager.has_collection():
            self.milvus_manager.create_collection(dense_dim=len(dense_embeddings[0]))
        
        logger.info(f"Inserting {len(milvus_data)} chunks into Milvus...")
        self.milvus_manager.insert(milvus_data)
        
        # 6. Mark as processed
        self._mark_as_processed(doc_md5)
        
        logger.info("Insertion complete and MD5 marked.")

    def close(self):
        self.milvus_manager.disconnect()

if __name__ == "__main__":
    # Test
    processor = DataEmbedding()
    from agent.Loader.doc_loader import DocumentLoader
    doc_loader = DocumentLoader()

    test_text = doc_loader.load(r"src\agent\data\test.pdf")
    processor.process_document(test_text, {"filename": "test.pdf", "file_type": "pdf"})
    processor.close()

